import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CartProvider } from '../context/CartContext';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type ContainerProps = {
  children: React.ReactNode; //👈 children prop typr
};

const Container = (props: ContainerProps) => { //👈 prop definition
  return (
    <CartProvider>
      {props.children}
      </CartProvider>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Container>
           {children}
        </Container>
      </body>
    </html>
  )
}
